language: python
python: 3.7
dist: xenial
sudo: true
script:
    - python3 -m venv env
    - source env/bin/activate
    - pip install --upgrade pip
    - pip install -r requirements.txt
    - python3 -m pytest 26_Continuous_Integration/test_remote_grid.py -s -v