language: python
python: 3.7
dist: xenial
sudo: true
script:
    - pip install pipenv
    - pipenv install --ignore-pipfile
    - pipenv run pytest 13_Selenium_remote_start/BrowserStack/test_remote_grid.py